const uuid = require('uuid/v4')

const gc2019 = [
  {key:1,active:false,date:27,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:2,active:false,date:28,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:3,active:false,date:29,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:4,active:false,date:30,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:5,active:true,date:31,type:'ocsa_grid_cal_item_mark',title:'Travel Day',desc:'Doug and Terry travel to Kingman, AZ',miles:'325',effort:'easy',time:'5'},
  {key:6,active:true,date:1,type:'ocsa_grid_cal_item_mark',title:'Travel Day',desc:'Doug and Terry travel to GC, AZ. Rohan and group travel to GC, AZ',miles:'173/1621',effort:'easy/moderate',time:'3/25'},
  {key:7,active:true,date:2,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 1',desc:'South Kaibab to Bright Angel',miles:'7.4',effort:'strenuous',time:'6'},
  {key:8,active:true,date:3,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 2',desc:'Bright Angel to Clear Creek',miles:'9.4',effort:'strenuous',time:'8'},
  {key:9,active:true,date:4,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 3',desc:'Clear Creek',miles:'4-5',effort:'easy',time:'3'},
  {key:10,active:true,date:5,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 4',desc:'Clear Creek',miles:'5-7',effort:'moderate',time:'4-6'},
  {key:11,active:true,date:6,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 5',desc:'Clear Creek',miles:'5-7',effort:'moderate',time:'4-6'},
  {key:12,active:true,date:7,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 6',desc:'Clear Creek',miles:'5-7',effort:'moderate',time:'4-6'},
  {key:13,active:true,date:8,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 7',desc:'Clear Creek to Bright Angel',miles:'9.4',effort:'strenuous',time:'8'},
  {key:14,active:true,date:9,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 8',desc:'Bright Angel to Indian Gardens',miles:'5.1',effort:'strenuous',time:'4'},
  {key:15,active:true,date:10,type:'ocsa_grid_cal_item_mark',title:'Canyon Day 9',desc:'Indian Gardens to GC Lodge',miles:'4.8',effort:'strenuous',time:'4'},
  {key:16,active:true,date:11,type:'ocsa_grid_cal_item_mark',title:'Travel Day',desc:'Doug and Terry travel home from Kingman, AZ',miles:'325',effort:'easy',time:'5'},
  {key:17,active:false,date:12,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:18,active:false,date:13,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:19,active:false,date:14,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:20,active:false,date:15,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:21,active:false,date:16,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:22,active:false,date:17,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:23,active:false,date:18,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:24,active:false,date:19,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:25,active:false,date:20,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:26,active:false,date:21,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:27,active:false,date:22,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:28,active:false,date:23,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:29,active:false,date:24,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:30,active:false,date:25,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:31,active:false,date:26,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:32,active:false,date:27,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:33,active:false,date:28,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:34,active:false,date:29,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''},
  {key:35,active:false,date:30,type:'ocsa_grid_cal_item',title:'',desc:'',miles:'',effort:'',time:''}
]

module.exports = { gc2019 }
